name: build executable file

on:
  push:
    tags:
      - 'v*' # Trigger when push tag start with v (etc. v0.1.0)
  workflow_dispatch: # Manual
  
permissions:
  contents: write
  
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install Dependencies
        run: uv export --no-hashes -o requirements.txt && pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.pyw
          mode: onefile

          low-memory: true
          # 经测试使用mingw64可以避免堆内存问题
          mingw64: true
          enable-plugins: tk-inter
          # 包含代码依赖包
          include-package: |
            UnityPy.resources
            tkinterdnd2
          # 包含依赖包的数据文件
          include-package-data: |
            UnityPy
            PIL
            tkinterdnd2
            archspec
            ttkbootstrap
          windows-console-mode: disable
          output-dir: build
          output-file: "BA-Modding-Toolkit.exe"
          assume-yes-for-downloads: true

      # 清理 Nuitka 生成的中间文件夹
      - name: Cleanup Nuitka Intermediate Files
        run: |
          Remove-Item -Path "build/main.build" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "build/main.dist" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "build/main.onefile-build" -Recurse -Force -ErrorAction SilentlyContinue
        shell: powershell

      # 复制外部资源文件夹到 build 目录
      - name: Copy External Resources
        run: |
          Copy-Item -Path "locales" -Destination "build/locales" -Recurse
          Copy-Item -Path "assets" -Destination "build/assets" -Recurse
        shell: powershell

      # 上传 Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BA-Modding-Toolkit-Windows-Build
          path: build/

      # 打包成 Zip
      - name: Zip Release Asset (When Trigger With Tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $tag_name = "${{ github.ref_name }}"
          cd build
          Compress-Archive -Path * -DestinationPath "../BA-Modding-Toolkit-$tag_name.zip"
        shell: powershell

      # 上传 Zip
      - name: Upload Release Asset (When Trigger With Tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: BA-Modding-Toolkit-${{ github.ref_name }}.zip